# -*- coding: utf-8 -*-
# Part of Softhealer Technologies.
{
    "name": "Sales Product Profit Report",
    "author": "Softhealer Technologies",
    "website": "https://www.softhealer.com",
    "support": "support@softhealer.com",
    "category": "Sales",
    "summary": "Sale Profit Report,Sale Order Profit Report,SO Profit Report,Product Profitability Analysis Report,Product Profit Analysis,Customer Profit Report,Print Sale Profit,Print Sale Order Profit,Quotation Profit Report Odoo",
    "description": """In this module, you can generate and print product sales profit reports in PDF as well as excel format. You can generate reports between any date range. Report generated by customers, products or both. We provide the option to print reports of more than one company.""",
    "version": "16.0.3",
    "depends": [
        'sale_management'
    ],
    "data": [
        'security/ir.model.access.csv',
        'security/sh_sale_product_profit_groups.xml',
        'data/sale_order_data.xml',
        'report/sh_sales_product_profit_templates.xml',
        'wizard/sh_sales_product_profit_wizard_views.xml',
        'views/sale_order_line_views.xml',
        'views/sh_sale_product_profit_views.xml',
    ],
    "images": ["static/description/background.png", ],
    "license": "OPL-1",
    "application" : True,
    "auto_install": False,
    "installable" : True,
    "price": 25,
    "currency": "EUR"
}
