{
    'name': 'Customer Vendor Statements',
    'version': '1.0',
    'summary': 'Display and print customer and vendor statements and aged balance, different status: all status, draft, posted or canceled',
    'description': "This module display customer and vendor Statements",
    'category': 'Accounting',
    'images': [
        'static/description/main_screenshot.gif',
        'static/description/main_screenshot.png',
        'static/description/screenshot1.png',
        'static/description/screenshot2.png',
        'static/description/screenshot3.png',
    ],
    'author': 'FireBits',
    'license': 'OPL-1',
    'company': 'FireBits',
    'maintainer': 'FireBits',
    'support': 'support@firebits.net',
    'sequence': -3,
    'website': 'https://firebits.net',
    'live_test_url': 'https://youtu.be/lIyCf0lAfeE',
    'depends': ['account'],
    'demo': [],
    'data': [
        'views/res_partner_view.xml',
        'report/partner_ledger.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
    ],
    "price": 9,
    "currency": 'EUR',
    'installable': True,
    'auto_install': False
}
